import Programming.configuration as conf

FC1_FEATURES = 1300
CON_FIRST_STRIDE = 2
CON1_WINDOW = 5
CONV_FIRST_DEPTH = 75
POOL_FIRST_SIZE = 2
CONV_SECOND_DEPTH = 150
POOL_SEC_SIZE = 2
NUM_CHANNELS = 1
DROPOUT_PROBABILITY = 0.5
MOMENTUM = 0.95
CONV_FIRST_FILTER_SIZE = 15
CONV_SECOND_FILTER_SIZE = 5
BATCH_SIZE = 100
EVAL_BATCH_SIZE = 151
BASE_LEARNING_RATE = 0.0001
DECAY_STEP_X_TIMES_TRAIN_SIZE = 8
DECAY_RATE = 0.6
EVAL_FREQUENCY = 30
VALIDATION_FREQUENCY = 5
USE_TEST_DATA = False
TRAIN_VALIDATION_CONDITION = 15

SCALE = 2
IMAGE_HEIGHT = 16 * SCALE
IMAGE_WIDTH = 16 * SCALE
if conf.CROPPED_VERSION:
    SOURCE_FOLDER_NAME = "../Datasets/Cropped datasets/" + conf.SUB_FOLDER + "Dataset_" + str(IMAGE_WIDTH) + "_" + str(
        IMAGE_HEIGHT) + "/"
