# configuration_network_edges.py
SCALE = 5
FC1_FEATURES = 1300
CON_FIRST_STRIDE = 2 * SCALE
CONV_FIRST_DEPTH = 75
POOL_FIRST_SIZE = 2
CONV_SECOND_DEPTH = 150
POOL_SEC_SIZE = 2
IMAGE_HEIGHT = 32 * SCALE
IMAGE_WIDTH = 32 * SCALE
NUM_CHANNELS = 1
DROPOUT_PROBABILITY = 0.85
