# configuration_network_edges.py
SCALE = 2
FC1_FEATURES = 1300
CON_FIRST_STRIDE = 2
CON1_WINDOW = 5
CONV_FIRST_DEPTH = 75
POOL_FIRST_SIZE = 2
CONV_SECOND_DEPTH = 150
POOL_SEC_SIZE = 2
IMAGE_HEIGHT = 16 * SCALE
IMAGE_WIDTH = 16 * SCALE
NUM_CHANNELS = 1
DROPOUT_PROBABILITY = 0.5
MOMENTUM = 0.95